### ISSUE TITLE
Fix the search button 

### ISSUE THREAD

**Issue by ajay-droid** [palakg01/simple-search-page#4]
Style the search button using html , css and js

**Comment by ajay-droid** [comment]
can you tell me more about the search button ? @palakg01

**Comment by VipulKhandelwal1999** [comment]
Do you guys have any other issues which i can fix?

**Comment by palakg01** [comment]
Check the website link [https://palakg01.github.io/simple-search-page/](https://palakg01.github.io/simple-search-page/)
The search bar needs a clear button
